spring.application.name=intentory-service
server.port=8081

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/linktic}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:123456}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.show-sql=true

spring.jpa.hibernate.ddl-auto=create


logging.level.org.hibernate.SQL= DEBUG

management.endpoints.web.exposure.include=health,info,metrics.prometheus
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true
